name: ActionLogger
version: '1.0'
main: carnage.actionLogger.ActionLogger
api-version: '1.21'
description: Logs all player actions to a MySQL database with performance optimizations
author: 0C4rn4g3

commands:
  logviewer:
    description: View action logs for a player
    usage: /logviewer <playerName> [actionType]
    permission: actionlogger.view
    aliases: [logs, viewlogs]

  dashboard:
    description: Opens a link to the action logs web dashboard
    usage: /dashboard
    permission: actionlogger.dashboard
    aliases: [actiondashboard, logdash]

  logger:
    description: ActionLogger management and statistics commands
    usage: |
      /logger stats - View performance statistics
      /logger flush - Force flush queued logs
      /logger pool - View connection pool stats
    permission: actionlogger.admin

permissions:
  actionlogger.view:
    description: Allows viewing action logs
    default: op

  actionlogger.dashboard:
    description: Allows access to the dashboard URL
    default: op

  actionlogger.admin:
    description: Allows access to admin commands (/logger)
    default: op

  actionlogger.*:
    description: Grants all ActionLogger permissions
    default: op
    children:
      actionlogger.view: true
      actionlogger.dashboard: true
      actionlogger.admin: true