name: ActionLogger
version: '1.0'
main: cat.daisy.core.Core
api-version: '1.21'
description: An ActionLogging plugin
authors: [ Daisy ]
website: https://daisy.cat

# Dependencies
softdepend: [ PlaceholderAPI ]

# Libraries - These will be downloaded by the server
libraries:
  # Kotlin dependencies
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2

  # Database dependencies
  - com.zaxxer:HikariCP:7.0.2
  - org.xerial:sqlite-jdbc:3.51.0.0